persistence:
  accessMode: "ReadWriteOnce"

storageClass:
  enabled: false
#  name: "standard"
#  provisioner: "kubernetes.io/host-path"
#  reclaimPolicy: "Delete"
#  volumeBindingMode: "Immediate"

syslogng:
  enabled: false

api:
  persistence:
    size: 1Mi
db:
  persistence:
    size: 1Mi

gitd:
  persistence:
    size: 1Mi
