name: Lint and Test Charts

on:
  push:
    branches:
      - '**'
    # paths:
    #   - 'netpicker-chart/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required for ct

      - name: Fetch default branch
        run: |
          git fetch origin ${{ github.event.repository.default_branch }}

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing lint
        run: |
          ct lint #\
            #--target-branch ${{ github.event.repository.default_branch }} \
            #--charts ./netpicker-chart

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0

      - name: Run chart-testing install
        run: |
          ct install #\
            #--target-branch ${{ github.event.repository.default_branch }} \
            #--chart-dirs ./netpicker-chart
